name: Reporte HxH - LSP26

on:
  workflow_dispatch:      # Permite rodar manualmente pelo GitHub

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: üßæ Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: üêç Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: üì¶ Instalar depend√™ncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright gspread oauth2client pytz
          playwright install chromium

      - name: üîê Adicionar credenciais do Google Sheets (hxh.json)
        shell: bash
        run: |
          echo "$GCP_JSON_BASE64" | base64 -d > hxh.json
        env:
          GCP_JSON_BASE64: ${{ secrets.GCP_JSON_BASE64 }}

      - name: ‚ñ∂Ô∏è Executar script Python
        run: xvfb-run python main.py
        env: # <--- ALTERA√á√ÉO ADICIONADA AQUI
          OPS_ID: ${{ secrets.OPS_ID }}
          OPS_SENHA: ${{ secrets.OPS_SENHA }}      
